name: Gold Price Bot

on:
  schedule:
    # Türkiye Saati ile 09:00 , 13.00 , 16.00 , 22.00
    - cron: '0 6,10,13,19 * * *'
  workflow_dispatch: # Manuel başlatma imkanı

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Kontrol Et
        uses: actions/checkout@v3

      - name: Python'u Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: pip install requests

      - name: Botu Çalıştır
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python gold_bot.py